@host =http://localhost:8000

###
GET {{host}}/api/genres/ http/1.1

### 
POST {{host}}/api/genres/ http/1.1
Content-Type: application/json

{
  "name": "Rap via guitar"
}

###
GET {{host}}/api/genres/1 http/1.1

###
DELETE  {{host}}/api/genres/26 http/1.1

### 
PATCH  {{host}}/api/genres/26 http/1.1
Content-Type: application/json

{
  "name": "Guitar rap"
}